apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aok-ml-dev
  namespace: argocd

spec:
  project: default
  source:
    repoUrl: https://github.com/Lausi95/argo-test.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: aok-ml-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

